export const menuSections = [
  {id:'starters', title:'Starters', kicker:'A good starter is a good start', image:'diner-03.jpg', items:[['Fries','$3','Golden French fries, served with ketchup.'],['Curly Fries','$5.5','Imported curly fries, served with cocktail sauce.'],['Chicken Tenders','$6.5','Four breaded chicken tenders with honey mustard.'],['Mozzarella Sticks','$5.5','Four mozzarella sticks with thousand island.'],['Rkakat','$6','Four homemade cheese rolls.'],['Hummus','$3.5','Homemade hummus with olive oil and bread.'],['Grilled Potatoes','$3','Local grilled potatoes with garlic paste.']]},
  {id:'salads', title:'Salads', kicker:'Fresh, bright, made daily', image:'diner-05.jpg', items:[['Fattouch','$7.5','Rocket, lettuce, tomatoes, cucumber, purslane, radish, fried bread and pomegranate dressing.'],['Tabboule','$7','Fresh parsley, tomato, onion and burghul with lemon-oil dressing.'],['Caesar','$6.5','Iceberg lettuce, croutons, parmesan and Caesar dressing.'],['Chicken Caesar','$9.5','Caesar salad with grilled chicken.'],['Quinoa','$9.5','Quinoa, greens, grilled halloumi and chicken with balsamic.'],['Mexican','$10.5','Grilled chicken, avocado, cheddar, red beans, corn and tortilla.']]},
  {id:'wraps', title:'Wraps & baguettes', kicker:'Wrapped with love', image:'diner-07.jpg', items:[['BBQ Wrap','$8.5','Crispy chicken, iceberg, corn, cheddar, honey mustard and BBQ sauce.'],['Crispy Wrap','$8.5','Crispy chicken, melted cheese, pickles, tomato and special sauce.'],['Smokey Loaded','$9.5','Beef patty, crispy onion, bacon, cheddar, mozzarella sticks and smoky BBQ.'],['Honey Chicken','$8.5','Chicken tenders, cheddar, iceberg, pickles and honey mustard.'],['Meet the Meat','$11','Grilled steak, onion, tomato, mushroom, cheddar and steak sauce.'],['Philly Chicken','$9.5','Marinated chicken, vegetables, mozzarella and chili sauce.']]},
  {id:'subs', title:'Subs', kicker:'The hunger terminator', image:'diner-10.jpg', items:[['Chicken Sub','$8.5','Grilled chicken, iceberg, tomato, pickles, mozzarella and garlic mayo.'],['Chicken Escalope Al Massoud','$8.5','Breaded chicken, cheddar, fries, coleslaw and Al Massoud sauces.'],['Chicken Supreme','$9','Grilled chicken, lettuce, pickles, tomato, fries, ham and cheese.'],['Francisco','$9','Chicken, corn, pickles, lettuce, mozzarella and soy sauce.'],['Fajita','$9','Marinated chicken, bell pepper, melted cheese and avocado-mayo.'],['BBQ Cheesy Blast','$11','Beef patty, bacon, cheddar, mozzarella sticks, BBQ and smoky sauce.']]},
  {id:'burgers', title:'Burgers', kicker:'Big, bold, seriously good', image:'diner-12.jpg', items:[['Chicken','$6','Grilled chicken breast, lettuce, pickles and garlic mayo.'],['Crispy Chicken','$6.5','Crispy chicken, cheddar, iceberg, pickles, chipotle and honey mustard.'],['Swiss Mushroom','$9','Grilled beef, emmental, sautéed onion and mushroom with Swiss sauce.'],['Simple Smashed','$7.5','Two smashed beef patties, double cheddar, pickles, onion and smoky sauce.'],['Al Massoud Smashed','$10','Two smashed patties, cheddar, crispy onion, bacon, mozzarella sticks and BBQ.'],['Beef Mexican','$9.5','Beef patty, cheddar, avocado-mayo, vegetables, tortilla chips and sriracha.']]},
  {id:'sandwiches', title:'Sandwiches', kicker:'The legends you come back for', image:'diner-14.jpg', items:[['Kaaket Al Massoud','$5.5','Chicken, pickles, garlic cream and Al Massoud special sauce.'],['Djej Al Massoud','$5.5','Al Massoud chicken, pickles, garlic cream and special sauce.'],['Djej','$5.25','Chicken, pickles and garlic cream.'],['Taouk','$5.5','Marinated chicken, pickles, fries, coleslaw and garlic paste.'],['Kabab Orfali','$6','Kabab, hummus, grilled tomato, eggplant, chilli pepper and onion.'],['Kafta','$5.25','Kafta, hummus, tomato, pickles and biwaz.']]},
  {id:'platters', title:'Platters', kicker:'Straight from the grill', image:'diner-16.jpg', items:[['Boneless Farrouj Al Massoud','$21','Boneless chicken, garlic bread, fries, coleslaw, pickles and signature garlic.'],['Boneless Farrouj Original','$21','Boneless chicken, garlic bread, garlic cream, fries, coleslaw and pickles.'],['Farrouj Al Massoud','$19','Whole chicken, garlic bread, fries, coleslaw, pickles and Al Massoud garlic.'],['Taouk','$10.5','Chicken skewers with garlic bread, garlic paste, fries, coleslaw and pickles.'],['Kafta','$11','Kafta skewers with grilled vegetables, hummus, pickles and tabbouleh.'],['Mixed Grill Veal','$19','Taouk, kabab and veal skewers with grilled vegetables and sides.']]},
  {id:'dessert', title:'Dessert & drinks', kicker:'Save room for this', image:'diner-18.jpg', items:[['Fudge Cake','$8','Served warm with a vanilla scoop.'],['Cookie Bomb','$8','Topped with caramel sauce and served with a vanilla scoop.'],['Fresh Orange','$3','Freshly squeezed orange juice.'],['Fresh Lemonade','$3','Fresh lemonade.'],['Soft drinks','$1.3','Pepsi, 7Up, Miranda and Diet options.'],['Ice Tea','$1.5','Classic iced tea.']]}
];
