'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowDown,Pause,Play,Phone,MapPin} from 'lucide-react';
const MENU='https://almassoud.com/menu/';
const dishes=[{name:'Boneless Farrouj',note:'THE SIGNATURE',image:'farrouj',description:'Flame-grilled chicken, garlic bread, fries, pickles and our signature garlic.'},{name:'Djej Al Massoud',note:'ALL-TIME FAVOURITE',image:'djej',description:'Al Massoud chicken, pickles, garlic cream and our special sauce.'},{name:'Taouk',note:'STRAIGHT FROM THE GRILL',image:'taouk',description:'Marinated chicken breast, fries, coleslaw, pickles and garlic paste.'}];
export default function Home(){
 const scene=useRef<HTMLElement>(null), video=useRef<HTMLVideoElement>(null);
 const [paused,setPaused]=useState(false),[reduced,setReduced]=useState(false);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const change=()=>{setReduced(media.matches);setPaused(media.matches)};change();media.addEventListener('change',change);let frame=0;const render=()=>{frame=0;const el=scene.current;if(!el)return;const distance=Math.max(1,el.offsetHeight-window.innerHeight);const p=Math.min(1,Math.max(0,-el.getBoundingClientRect().top/distance));el.style.setProperty('--progress',String(media.matches?0:p))};const scroll=()=>{if(!frame)frame=requestAnimationFrame(render)};render();window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));return()=>{media.removeEventListener('change',change);window.removeEventListener('scroll',scroll);window.removeEventListener('resize',scroll);cancelAnimationFrame(frame);observer.disconnect()}},[]);
 useEffect(()=>{if(!video.current)return;if(paused||reduced)video.current.pause();else video.current.play().catch(()=>setPaused(true))},[paused,reduced]);
 return <main id="top"><a className="skip-link" href="#best-sellers">Skip to food</a><header><a className="brand" href="#top" aria-label="Al Massoud home"><img src="/logo.png" alt="Al Massoud — good food made good" width="166" height="66"/></a><nav aria-label="Main navigation"><a href={MENU}>Our menu</a><a href="https://almassoud.com/brand/">Our story</a><a href="https://almassoud.com/restaurants/">Find us</a></nav><a className="order" href="tel:1632">ORDER NOW <ArrowUpRight size={16}/></a></header>
 <section ref={scene} className="hero-scene" aria-labelledby="hero-title"><div className="hero"><div className="film"><img className="poster" src="/hero-poster.jpg" alt="Golden flame-grilled chicken with crisp skin and rising steam" fetchPriority="high" width="1920" height="1080"/><video ref={video} className="hero-video" muted loop playsInline autoPlay={!reduced} preload="metadata" poster="/hero-poster.jpg" aria-hidden="true"><source src="/hero.mp4" type="video/mp4"/></video></div><div className="lighting"/><div className="shade"/><div className="copy"><p className="eyebrow"><span/> LEBANESE SOUL. STRAIGHT FROM THE GRILL.</p><h1 id="hero-title">Good food.<br/><em>Great fire.</em></h1><p className="intro">Golden. Juicy. Flame-kissed.<br/>This is how cravings begin.</p><div className="actions"><a className="button light" href={MENU}>VIEW MENU <ArrowUpRight size={18}/></a><a className="button red" href="tel:1632">ORDER NOW <ArrowUpRight size={18}/></a></div></div><div className="food-caption"><span className="fine-line"/><p>THE ART OF THE GRILL.<small>Good food made good.</small></p></div><button className="motion-toggle" onClick={()=>{setReduced(false);setPaused(!paused)}} aria-label={paused?'Play hero animation':'Pause hero animation'}>{paused?<Play size={14}/>:<Pause size={14}/>}<span>{paused?'PLAY':'PAUSE'}</span></button><div className="hero-bottom"><span>FIRE. FLAVOUR. AL MASSOUD.</span><a href="#best-sellers">SCROLL TO GET HUNGRY <ArrowDown size={15}/></a><a href="tel:1632">LEBANON <span className="divider">/</span> 1632</a></div><div className="bridge"><p className="eyebrow">A LITTLE CLOSER. A LOT HUNGRIER.</p><h2>Follow the flavour.</h2></div></div></section>
 <section id="best-sellers" className="bestsellers"><div className="section-top" data-reveal><div><p className="eyebrow">THE ONES YOU COME BACK FOR</p><h2>Best sellers<span>.</span></h2></div><a className="text-link" href={MENU}>EXPLORE THE FULL MENU <ArrowUpRight size={20}/></a></div><div className="food-grid">{dishes.map((dish,i)=><a data-reveal className="dish" href={MENU} key={dish.name} style={{transitionDelay:`${i*90}ms`}}><div className="dish-image"><img src={`/${dish.image}.webp`} alt={dish.name} width="1021" height="943" loading="lazy"/><span className="dish-number">0{i+1}</span><span className="dish-arrow"><ArrowUpRight size={22}/></span></div><p className="dish-note">{dish.note}</p><h3>{dish.name}</h3><p className="dish-description">{dish.description}</p></a>)}</div></section>
 <section className="closing" data-reveal><div><p className="eyebrow">THAT FIRST BITE IS CALLING.</p><h2>Come hungry.<br/><em>Leave happy.</em></h2></div><div className="closing-actions"><p>Your favourites, fresh from the grill.</p><a className="button light" href="tel:1632"><Phone size={18}/> ORDER NOW · 1632 <ArrowUpRight size={18}/></a><a className="location-link" href="https://almassoud.com/restaurants/"><MapPin size={17}/> FIND YOUR AL MASSOUD <ArrowUpRight size={17}/></a></div></section>
 <footer><div className="footer-top"><a href="#top" className="footer-brand"><img src="/logo.png" alt="Al Massoud" width="180" height="67"/></a><p>Good food made good.<br/><span>Made to bring us together.</span></p><a className="instagram" href="https://www.instagram.com/almassoudgrill/">FOLLOW THE FLAVOUR <ArrowUpRight size={17}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Al Massoud</span><nav aria-label="More about Al Massoud"><a href="https://almassoud.com/loyalty-corner/">Loyalty corner</a><a href="https://almassoud.com/careers/">Careers</a><a href="https://almassoud.com/franchise/">Franchise</a><a href="https://almassoud.com/contact/">Contact</a></nav><a href="#top">BACK TO TOP ↑</a></div></footer></main>
}
