'use client';
import {SiteHeader} from '../components/site-header';
import {useHeroPlayback} from '../hooks/use-hero-playback';
import {ArrowUpRight,ArrowDown,Pause,Play,Phone,MapPin} from 'lucide-react';
const MENU='/menu';
const dishes=[{name:'Boneless Farrouj',anchor:'platters-boneless-farrouj-al-massoud',note:'THE SIGNATURE',image:'farrouj',description:'Flame-grilled chicken, garlic bread, fries, pickles and our signature garlic.'},{name:'Djej Al Massoud',anchor:'sandwiches-djej-al-massoud',note:'ALL-TIME FAVOURITE',image:'djej',description:'Al Massoud chicken, pickles, garlic cream and our special sauce.'},{name:'Taouk',anchor:'platters-taouk',note:'STRAIGHT FROM THE GRILL',image:'taouk',description:'Marinated chicken breast, fries, coleslaw, pickles and garlic paste.'}];
export default function Home(){
 const {scene,video,canvas,ready,paused,reduced,toggleMotion}=useHeroPlayback();
 return <main id="top"><link rel="preload" as="image" href="/hero-frames-v1/000.webp" media="(pointer: coarse), (max-width: 900px)"/><a className="skip-link" href="#best-sellers">Skip to food</a><SiteHeader/>
 <section ref={scene} data-phase="grill" className={`hero-scene assembly-scene${paused?' motion-paused':''}`} aria-labelledby="hero-title"><div className="hero"><div className="film"><img className="poster" src="/farrouj-poster.jpg" alt="Al Massoud boneless grilled farrouj served flat on a wooden board with fries, garlic sauce, coleslaw and bread" fetchPriority="high" width="1920" height="1080"/><video ref={video} className={`hero-video${ready?' is-ready':''}`} muted playsInline preload="auto" poster="/farrouj-poster.jpg" aria-hidden="true"><source src="/farrouj-assembly.mp4" type="video/mp4" media="(pointer: fine) and (min-width: 901px)"/></video><canvas ref={canvas} width="1920" height="1080" className={`hero-frame${ready?' is-ready':''}`} aria-hidden="true"/></div><div className="lighting"/><div className="shade"/><div className="copy"><p className="eyebrow"><span/> LEBANESE SOUL. STRAIGHT FROM THE GRILL.</p><h1 id="hero-title">Good food.<br/><em>Great fire.</em></h1><p className="intro">Golden. Juicy. Flame-kissed.<br/>This is how cravings begin.</p><div className="actions"><a className="button light" href={MENU}>VIEW MENU <ArrowUpRight size={18}/></a><a className="button red" href="tel:1632">ORDER NOW <ArrowUpRight size={18}/></a></div></div><div className="food-caption"><span className="fine-line"/><p>THE ART OF THE GRILL.<small>Good food made good.</small></p></div><button className="motion-toggle" onClick={toggleMotion} aria-label={reduced?'Play animation':paused?'Resume scroll animation':'Pause scroll animation'} aria-pressed={paused}>{paused||reduced?<Play size={14}/>:<Pause size={14}/>}<span>{reduced?'PLAY ANIMATION':paused?'RESUME':'PAUSE MOTION'}</span></button><div className="hero-bottom"><span>FIRE. FLAVOUR. AL MASSOUD.</span><a href="#best-sellers">SCROLL TO BUILD YOUR PLATTER <ArrowDown size={15}/></a><a href="tel:1632">LEBANON <span className="divider">/</span> 1632</a></div><div className="ingredient-copy"><p className="eyebrow">EVERY PART. PURE GOODNESS.</p><h2>Flame-grilled.<br/><em>Perfectly paired.</em></h2><p>Our boneless farrouj. Golden fries.<br/>Creamy garlic. All the good stuff.</p></div><div className="bridge"><p className="eyebrow">THE WHOLE CRAVING. ON ONE BOARD.</p><h2>Made to share.<br/>Hard to resist.</h2></div><div className="scene-progress" aria-hidden="true"><span/></div></div></section>
 <section id="best-sellers" className="bestsellers"><div className="section-top" data-reveal><div><p className="eyebrow">THE ONES YOU COME BACK FOR</p><h2>Made for<br/><em>cravings.</em></h2></div><a className="text-link" href={MENU}>EXPLORE THE FULL MENU <ArrowUpRight size={20}/></a></div><div className="food-grid">{dishes.map((dish,i)=><a data-reveal className="dish" href={`${MENU}#${dish.anchor}`} key={dish.name}><div className="dish-meta"><span>0{i+1}</span><p>{dish.note}</p></div><div className="dish-image"><img src={`/${dish.image}.webp`} alt={dish.name} width="1021" height="943" loading="lazy"/><span className="dish-arrow"><ArrowUpRight size={22}/></span></div><div className="dish-copy"><h3>{dish.name}</h3><p className="dish-description">{dish.description}</p><span className="dish-order">VIEW DISH</span></div></a>)}</div></section>
 <section className="closing" data-reveal><div><p className="eyebrow">THAT FIRST BITE IS CALLING.</p><h2>Come hungry.<br/><em>Leave happy.</em></h2></div><div className="closing-actions"><p>Your favourites, fresh from the grill.</p><a className="button light" href="tel:1632"><Phone size={18}/> ORDER NOW · 1632 <ArrowUpRight size={18}/></a><a className="location-link" href="/locations"><MapPin size={17}/> FIND YOUR AL MASSOUD <ArrowUpRight size={17}/></a></div></section>
 <footer><div className="footer-top"><a href="/#top" className="footer-brand"><img src="/logo.png" alt="Al Massoud" width="180" height="67"/></a><p>Good food made good.<br/><span>Made to bring us together.</span></p><a className="instagram" href="https://www.instagram.com/almassoudgrill/">FOLLOW THE FLAVOUR <ArrowUpRight size={17}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Al Massoud</span><nav aria-label="More about Al Massoud"><a href="https://almassoud.com/loyalty-corner/" target="_blank" rel="noopener noreferrer">Loyalty corner</a><a href="https://almassoud.com/careers/" target="_blank" rel="noopener noreferrer">Careers</a><a href="https://almassoud.com/franchise/" target="_blank" rel="noopener noreferrer">Franchise</a><a href="https://almassoud.com/contact/" target="_blank" rel="noopener noreferrer">Contact</a></nav><a href="#top">BACK TO TOP ↑</a></div></footer></main>
}
