'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowDown,Pause,Play,Phone,MapPin} from 'lucide-react';
const MENU='https://almassoud.com/menu/';
const dishes=[{name:'Boneless Farrouj',note:'THE SIGNATURE',image:'farrouj',description:'Flame-grilled chicken, garlic bread, fries, pickles and our signature garlic.'},{name:'Djej Al Massoud',note:'ALL-TIME FAVOURITE',image:'djej',description:'Al Massoud chicken, pickles, garlic cream and our special sauce.'},{name:'Taouk',note:'STRAIGHT FROM THE GRILL',image:'taouk',description:'Marinated chicken breast, fries, coleslaw, pickles and garlic paste.'}];
export default function Home(){
 const scene=useRef<HTMLElement>(null), video=useRef<HTMLVideoElement>(null);
 const progress=useRef(0), targetTime=useRef(0), motionPaused=useRef(false), prefersReduced=useRef(false);
 const [paused,setPaused]=useState(false),[reduced,setReduced]=useState(false),[ready,setReady]=useState(false);
 const seekToScroll=()=>{const film=video.current;if(!film||motionPaused.current||prefersReduced.current||!Number.isFinite(film.duration)||film.seeking)return;if(Math.abs(film.currentTime-targetTime.current)>.055)film.currentTime=targetTime.current};
 useEffect(()=>{
  const media=window.matchMedia('(prefers-reduced-motion: reduce)');
  const change=()=>{prefersReduced.current=media.matches;setReduced(media.matches);if(media.matches)video.current?.pause()};change();media.addEventListener('change',change);
  let frame=0;
  const render=()=>{frame=0;const el=scene.current,film=video.current;if(!el)return;const distance=Math.max(1,el.offsetHeight-window.innerHeight);const p=Math.min(1,Math.max(0,-el.getBoundingClientRect().top/distance));progress.current=p;if(motionPaused.current)return;el.style.setProperty('--progress',String(media.matches?0:p));el.dataset.phase=p<.25?'grill':p<.68?'ingredients':'platter';if(!film||media.matches||!Number.isFinite(film.duration))return;film.pause();targetTime.current=Math.min(Math.max(0,film.duration-.06),p*film.duration);seekToScroll()};
  const scroll=()=>{if(!frame)frame=requestAnimationFrame(render)};
  const loaded=()=>{if(progress.current>.005)render()};
  const intro=()=>{const film=video.current;if(film&&progress.current<.005&&film.currentTime>=1.2)film.pause()};
  const ended=()=>video.current?.pause();
  const film=video.current;film?.addEventListener('loadedmetadata',loaded);film?.addEventListener('timeupdate',intro);film?.addEventListener('seeked',seekToScroll);film?.addEventListener('ended',ended);
  window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);
  const rect=elRect();if(rect<0)render();
  function elRect(){return scene.current?.getBoundingClientRect().top??0}
  return()=>{media.removeEventListener('change',change);window.removeEventListener('scroll',scroll);window.removeEventListener('resize',scroll);film?.removeEventListener('loadedmetadata',loaded);film?.removeEventListener('timeupdate',intro);film?.removeEventListener('seeked',seekToScroll);film?.removeEventListener('ended',ended);cancelAnimationFrame(frame)}
 },[]);
 const toggleMotion=()=>{const next=!paused;motionPaused.current=next;setPaused(next);video.current?.pause();if(!next)window.dispatchEvent(new Event('scroll'))};
 return <main id="top"><a className="skip-link" href="#best-sellers">Skip to food</a><header><a className="brand" href="#top" aria-label="Al Massoud home"><img src="/logo.png" alt="Al Massoud — good food made good" width="166" height="66"/></a><nav aria-label="Main navigation"><a href={MENU}>Our menu</a><a href="https://almassoud.com/brand/">Our story</a><a href="https://almassoud.com/restaurants/">Find us</a></nav><a className="order" href="tel:1632">ORDER NOW <ArrowUpRight size={16}/></a></header>
 <section ref={scene} data-phase="grill" className={`hero-scene assembly-scene${paused?' motion-paused':''}`} aria-labelledby="hero-title"><div className="hero"><div className="film"><img className="poster" src="/farrouj-poster.jpg" alt="Al Massoud boneless grilled farrouj served flat on a wooden board with fries, garlic sauce, coleslaw and bread" fetchPriority="high" width="1920" height="1080"/><video ref={video} className={`hero-video${ready?' is-ready':''}`} muted playsInline autoPlay={!reduced} preload="auto" poster="/farrouj-poster.jpg" onLoadedData={()=>setReady(true)} onError={()=>setReady(false)} aria-hidden="true"><source src="/farrouj-assembly.mp4" type="video/mp4"/></video></div><div className="lighting"/><div className="shade"/><div className="copy"><p className="eyebrow"><span/> LEBANESE SOUL. STRAIGHT FROM THE GRILL.</p><h1 id="hero-title">Good food.<br/><em>Great fire.</em></h1><p className="intro">Golden. Juicy. Flame-kissed.<br/>This is how cravings begin.</p><div className="actions"><a className="button light" href={MENU}>VIEW MENU <ArrowUpRight size={18}/></a><a className="button red" href="tel:1632">ORDER NOW <ArrowUpRight size={18}/></a></div></div><div className="food-caption"><span className="fine-line"/><p>THE ART OF THE GRILL.<small>Good food made good.</small></p></div><button className="motion-toggle" onClick={toggleMotion} aria-label={paused?'Resume scroll animation':'Pause scroll animation'} aria-pressed={paused}>{paused?<Play size={14}/>:<Pause size={14}/>}<span>{paused?'RESUME':'PAUSE MOTION'}</span></button><div className="hero-bottom"><span>FIRE. FLAVOUR. AL MASSOUD.</span><a href="#best-sellers">SCROLL TO BUILD YOUR PLATTER <ArrowDown size={15}/></a><a href="tel:1632">LEBANON <span className="divider">/</span> 1632</a></div><div className="ingredient-copy"><p className="eyebrow">EVERY PART. PURE GOODNESS.</p><h2>Flame-grilled.<br/><em>Perfectly paired.</em></h2><p>Our boneless farrouj. Golden fries.<br/>Creamy garlic. All the good stuff.</p></div><div className="bridge"><p className="eyebrow">THE WHOLE CRAVING. ON ONE BOARD.</p><h2>Made to share.<br/>Hard to resist.</h2></div><div className="scene-progress" aria-hidden="true"><span/></div></div></section>
 <section id="best-sellers" className="bestsellers"><div className="section-top" data-reveal><div><p className="eyebrow">THE ONES YOU COME BACK FOR</p><h2>Best sellers<span>.</span></h2></div><a className="text-link" href={MENU}>EXPLORE THE FULL MENU <ArrowUpRight size={20}/></a></div><div className="food-grid">{dishes.map((dish,i)=><a data-reveal className="dish" href={MENU} key={dish.name} style={{transitionDelay:`${i*90}ms`}}><div className="dish-image"><img src={`/${dish.image}.webp`} alt={dish.name} width="1021" height="943" loading="lazy"/><span className="dish-number">0{i+1}</span><span className="dish-arrow"><ArrowUpRight size={22}/></span></div><p className="dish-note">{dish.note}</p><h3>{dish.name}</h3><p className="dish-description">{dish.description}</p></a>)}</div></section>
 <section className="closing" data-reveal><div><p className="eyebrow">THAT FIRST BITE IS CALLING.</p><h2>Come hungry.<br/><em>Leave happy.</em></h2></div><div className="closing-actions"><p>Your favourites, fresh from the grill.</p><a className="button light" href="tel:1632"><Phone size={18}/> ORDER NOW · 1632 <ArrowUpRight size={18}/></a><a className="location-link" href="https://almassoud.com/restaurants/"><MapPin size={17}/> FIND YOUR AL MASSOUD <ArrowUpRight size={17}/></a></div></section>
 <footer><div className="footer-top"><a href="#top" className="footer-brand"><img src="/logo.png" alt="Al Massoud" width="180" height="67"/></a><p>Good food made good.<br/><span>Made to bring us together.</span></p><a className="instagram" href="https://www.instagram.com/almassoudgrill/">FOLLOW THE FLAVOUR <ArrowUpRight size={17}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Al Massoud</span><nav aria-label="More about Al Massoud"><a href="https://almassoud.com/loyalty-corner/">Loyalty corner</a><a href="https://almassoud.com/careers/">Careers</a><a href="https://almassoud.com/franchise/">Franchise</a><a href="https://almassoud.com/contact/">Contact</a></nav><a href="#top">BACK TO TOP ↑</a></div></footer></main>
}
